### ISSUE TITLE
Gamma Value

### ISSUE THREAD

**Issue by rishihahs** [EllaBot/true-online-td-lambda#2]
https://github.com/EllaBot/true-online-td-lambda/blob/optimization/true_online_td_lambda/true_online_td_lambda.py#L10

Isn't gamma supposed to be in the interval `[0, 1)`?

**Comment by nickswalker** [comment]
I pulled the parameters from [python-rl's implementation](https://github.com/amarack/python-rl/blob/master/pyrl/agents/sarsa_lambda.py). Does seem like a strange default. What was Matteo's suggestion?

**Comment by rishihahs** [comment]
The Wikipedia [article](http://en.wikipedia.org/wiki/SARSA#Discount_factor_.28gamma.29) explains it more.

"If the discount factor meets or exceeds 1, the Q values may diverge."

**Comment by rishihahs** [comment]
We could change it to `0.99`. That's what [pybrain](https://github.com/pybrain/pybrain/blob/master/pybrain/rl/learners/valuebased/qlambda.py) has by default (and it has lambda as `0.9`).
